### ISSUE TITLE
条件生成中自定义数据集标签制作

### ISSUE THREAD

**Issue by yangshenchang** [zoubohao/DenoisingDiffusionProbabilityModel-ddpm-#13]
大佬，请教一个问题，我正在使用你的算法生成车牌数据，在随机生成下效果还不错，现在要使用条件生活，为固定的车牌号生成对应车牌，但是这个工程中label条件只是单独的0-9的数字，请问一下如果要使用7-8位的车牌数据做条件进行生成，需要改哪些地方

**Comment by ONobody** [comment]
@yangshenchang 你好，请问这个怎样训练自己的数据集  数据种类只有8类的时候需要改那些谢谢

**Comment by yangshenchang** [comment]
@ONobody 看你自己的数据集，如果只是分类数据的话，直接用torchvision.datasets.ImageFolder函数读取就可以，8个类别在对应8个文件夹应该就能训练；如果你的类别比较复杂，比如像我的车牌一样，那就需要自定义dataset函数，将你的类别编码，然后对应修改modelcondition.py文件中cond_embedding的维度就可以了

**Comment by ONobody** [comment]
![blade](https://user-images.githubusercontent.com/108787020/222362692-2bd0bcc1-6623-43a8-bcb6-a901ecec9a79.png)
你好 我用1700多张图片训练了200个eopch  但生成的效果是这样的
 是我有那个地方不对吗

**Comment by ONobody** [comment]
@yangshenchang

**Comment by cainiao123s** [comment]
> @ONobody 看你自己的数据集，如果只是分类数据的话，直接用torchvision.datasets.ImageFolder函数读取就可以，8个类别在对应8个文件夹应该就能训练；如果你的类别比较复杂，比如像我的车牌一样，那就需要自定义dataset函数，将你的类别编码，然后对应修改modelcondition.py文件中cond_embedding的维度就可以了

您好，请问有没有遇到过我这个问题，张量维度不一致。Traceback (most recent call last):
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Main.py", line 41, in <module>
    main(model_config)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Main.py", line 34, in main
    train(modelConfig)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Diffusion\Train.py", line 87, in train
    loss = trainer(x_0).sum() / 1000.
  File "E:\APP\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Diffusion\Diffusion.py", line 46, in forward
    loss = F.mse_loss(self.model(x_t, t), noise, reduction='none')
  File "E:\APP\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Diffusion\Model.py", line 231, in forward
    h = torch.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 126 but got size 125 for tensor number 1 in the list.
