### ISSUE TITLE
自定义训练集，张量维度不统一

### ISSUE THREAD

**Issue by cainiao123s** [zoubohao/DenoisingDiffusionProbabilityModel-ddpm-#46]
0%|          | 0/224 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Main.py", line 41, in <module>
    main(model_config)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Main.py", line 34, in main
    train(modelConfig)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Diffusion\Train.py", line 87, in train
    loss = trainer(x_0).sum() / 1000.
  File "E:\APP\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Diffusion\Diffusion.py", line 46, in forward
    loss = F.mse_loss(self.model(x_t, t), noise, reduction='none')
  File "E:\APP\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\扩散模型\DenoisingDiffusionProbabilityModel-ddpm--main\Diffusion\Model.py", line 231, in forward
    h = torch.cat([h, hs.pop()], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 126 but got size 125 for tensor number 1 in the list.

Process finished with exit code 1
我个人认为是下采样的时候出现了问题，但是网络模型应该是被实践过无数次的，除非作者再改动的时候对U-net进行了微调，有没有研究者能一起讨论一下这个问题？

**Comment by zoubohao** [comment]
这个应该是你图片输入的大小（size）有点问题。你图片大小多大的。

**Comment by cainiao123s** [comment]
> 这个应该是你图片输入的大小（size）有点问题。你图片大小多大的。

嗯嗯，你说的对，哈哈。我调整了一下图像尺寸为正方形就好了
